<?php 
/**
 * This file is part of Kartaca WBVS
 *
 * Kartaca WBVS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca WBVS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca WBVS. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 */

if ($this->showSuccess) { ?>
	
	<h4>Well Done!</h4>
	<p class="alt">
		There is a final step you have to fulfill in order to join us! Go and check your emails, you will find the details there! We are awaiting on your return!
	</p>

<?php } else { ?>
	<h4>Please Fill this form to become one of us!</h4>

	<?php if ($this->shwoError !== null) { ?>
	    <div class="error">
	    	Don't take us as a fool! We have eyes watching over you. Correct the mistakes you have done below
	    </div>
	<?php } ?>

	<?=$this->form?>

<?php } ?>