<?php

//Now let's add my custom stylesheet
$this->headLink()->appendStylesheet($this->baseUrl() . "/style.css");

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Web Based Voting System</title>
    <!-- Blueprint css framework add on -->
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/print.css" type="text/css" media="print">
    <!--[if lt IE 8]>
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">

    <!-- And my custom style sheet -->
    <?php echo $this->headLink() ?>
</head>
<body>
    <div class="container">
        <h1>Web Based Voting System</h1>
        <h2 class="alt subheader">Be The Voter You Always Wanted To Be!</h2>
        <hr />
        <div id="header-title">
            <h3><?=$this->title?></h3>
        </div>
        <div id="header">
            <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>">Home</a></span> |
            <?php if (Zend_Auth::getInstance()->getIdentity()) { ?>
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/vote">Participate A Vote</a></span> |
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant/subscriptions">What I Voted</a></span> |
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant/logout">Say GoobBye!</a></span>
            <?php } else { ?>
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant">I want to Come In</a></span> | 
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant/register">I want to Join</a></span>
            <?php } ?>
        </div>
        <hr />
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="footer">
            <div class="promote alt">
                <a href="http://code.kartaca.com/zf-blog">Web Based Voting System</a>
            </div>
            <p>
                Proud to be a <a href="http://www.gnu.org/licenses/">GPL</a> software<br />
                <a href="http://www.kartaca.com">Kartaca</a>
            </p>
        </div>
    </div>
</body>
</html>