<?php
/**
 * This file is part of Kartaca WBVS
 *
 * Kartaca WBVS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca WBVS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca WBVS. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 */

//Now let's add my custom stylesheet
$this->headLink()->appendStylesheet($this->baseUrl() . "/style.css");

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Web Based Voting System</title>
    <!-- Blueprint css framework add on -->
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/print.css" type="text/css" media="print">
    <!--[if lt IE 8]>
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">
    <script src="<?=$this->baseUrl()?>/js/jquery-161-min.js" type="text/javascript"></script>
    <script src="<?=$this->baseUrl()?>/js/highcharts.js" type="text/javascript"></script>
    <!-- And my custom style sheet -->
    <?php echo $this->headLink() ?>
</head>
<body>
    <div class="container">
        <h1>Web Based Voting System</h1>
        <h2 class="alt subheader">Be The Voter You Always Wanted To Be!</h2>
        <hr />
        <div id="header-title">
            <h3><?=$this->title?></h3>
        </div>
        <div id="header">
            <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>">Home</a></span> |
            <?php if (Zend_Auth::getInstance()->getIdentity()) { ?>
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant/update">Update My Info</a></span> |
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/vote">Participate A Vote</a></span> |
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant/subscriptions">What I Voted</a></span> |
                <?php if (ADMIN_ENABLED === 1) { ?>
                    <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/vote">Manage Votes</a></span> |
                    <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/participant">Manage Participants</a></span> |
                <?php } ?>
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant/logout">Say GoobBye!</a></span>
            <?php } else { ?>
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant">I want to Come In</a></span> | 
                <span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/participant/register">I want to Join</a></span>
            <?php } ?>
        </div>
        <hr />
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="footer">
            <div class="promote alt">
                <a href="https://github.com/radalin/zf-examples">Kartaca WBVS</a>
            </div>
            <p>
                Proud to be a <a href="http://www.gnu.org/licenses/">GPL</a> software<br />
                <a href="http://www.kartaca.com">Kartaca</a>
            </p>
        </div>
    </div>
</body>
</html>