<?php 
/**
 * This file is part of Kartaca WBVS
 *
 * Kartaca WBVS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca WBVS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca WBVS. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 */
?>
<div class="export">
	<span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/participantedit?act=create">Create New</a></span> |
	<span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/export?type=p">Export</a></span>
</div>
<table>
	<tr>
		<th>ID</th>
		<th>Email</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Edit/Delete</th>
	</tr>
	<?php foreach ($this->participants as $_p) { ?>
		<tr>
			<td><?=$_p->id?></td>
			<td><?=$_p->email?></td>
			<td><?=$_p->fname?></td>
			<td><?=$_p->lname?></td>
			<td>
				<span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/participantedit?act=edit&pid=<?=$_p->id?>">Edit</a></span> | 
				<span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/participantedit?act=del&pid=<?=$_p->id?>">Delete</a></span>
			</td>
		</tr>
	<?php } ?>
</table>