<?php 
/**
 * This file is part of Kartaca WBVS
 *
 * Kartaca WBVS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca WBVS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca WBVS. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 */
?>
<?php if ($this->errorMsg) { ?>
<div class="error">
    <?php echo $this->errorMsg; ?>
</div>
<?php } ?>
<div class="span-8 colborder" style="width: 400px;">
    <?=$this->form?>
</div>
<div class="span-7 last" style="width: 300px;">
    <?php
        echo "<h6>Answers:</h6>";
        if ($this->answerEditingEnabled) { ?>
            <input type="text" id="answer-text"> <span class="alt"><a href="#" id="add-answer-btn">Add Answer</a></span>
            <ul id='answers-list'></ul>
        <?php } else {
            echo "<ul>";
            $_totalVoteCount = 0;
            foreach ($this->answers as $_a) {
                $_str = $_a->vote_count . " - " . $_a->text;
                echo "<li>" . $_str . "</li>";
                $_totalVoteCount += $_a->vote_count;
            }
            echo "</ul>";
        }
    ?>
    <div id="chart" style="width:100%;">
    </div>
</div>
<hr />
<?php if ($this->answers) { ?>
    <script>
        var chart;
        $(document).ready(function() {
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'chart',
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false
                },
                title: {
                    text: ''
                },
                tooltip: {
                    formatter: function() {
                        return this.y + ' % - <b>' + this.point.name + '</b>';
                    }
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            formatter: function() {
                                return this.y + ' % - <b>'+ this.point.name + '</b>';
                            }
                        }
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Vote Results',
                    data: [
                        <?php foreach ($this->answers as $_a) { ?>
                            <?="['{$_a->text}', " . (int) ($_a->vote_count * 100 / $_totalVoteCount) . "],"?>
                        <?php } ?>
                    ]
                }]
           });
        });
    </script>
<?php } else { ?>
    <script>
        var calculateAnswer = function() {
            var hiddenAnswerVal = "";
            $("#answers-list li span.val").each(function() {
                hiddenAnswerVal += (hiddenAnswerVal == "" ? "" : "----") + $(this).html();
            })
            $("#answers").val(hiddenAnswerVal);
        }
        $(document).ready(function() {
           $("#add-answer-btn").click(function() {
                var answer = $("#answer-text");
                $("#answers-list")
                    .append($("<li>")
                        .append(
                            $("<span>")
                                .attr("class", "val")
                                .html(answer.val())
                        )
                        .append(" - ")
                        .append(
                            $("<span>")
                                .attr("class", "alt")
                                .append(
                                    $("<a>")
                                        .attr("href", "#")
                                        .html("Remove")
                                        .click(function() {
                                            $(this).parent().parent().attr("class", "remove");
                                            $("#answers-list li.remove").remove();
                                            calculateAnswer();
                                        }
                                    )
                                )
                        )
                );
                answer.val("");
                calculateAnswer();
            }); 
            return false;
        });
    </script>
<?php } ?>