<?php 
/**
 * This file is part of Kartaca WBVS
 *
 * Kartaca WBVS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca WBVS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca WBVS. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 */
?>
<div class="export">
	<span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/voteedit?act=create">Create New</a></span> | 
	<span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/export?type=v">Export</a></span>
</div>
<table>
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Description</th>
		<th>Begining Date</th>
		<th>Expiring Date</th>
		<th>Edit/Delete</th>
	</tr>
	<?php foreach ($this->votes as $_v) { ?>
		<tr>
			<td><?=$_v->id?></td>
			<td><?=$_v->name?></td>
			<td><?=$_v->desc?></td>
			<td><?=$_v->begin_date?></td>
			<td><?=$_v->expire_date?></td>
			<td>
				<span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/voteedit?act=edit&vid=<?=$_v->id?>">Edit</a></span> | 
				<span class="alt"><a href="<?=APPLICATION_BASEURL_INDEX?>/admin/voteedit?act=del&vid=<?=$_v->id?>">Delete</a></span>
			</td>
		</tr>
	<?php } ?>
</table>