<?php 
/**
 * This file is part of Kartaca WBVS
 *
 * Kartaca WBVS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca WBVS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca WBVS. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 */

foreach ($this->votes as $v) { ?>
	<div class="vote-list">
		<!-- Linking with routes -->
	    <span class="alt large">
	    	<?=$v->name?>
	    </span>
	    <span class="small">
	    	| Time Span: <?=$v->begin_date?> - <?=$v->expire_date?>
	    </span>
	    <div class="body">
	    	<?=nl2br($v->desc)?>
	    </div>
	    <div>
	    	<a href="<?=APPLICATION_BASEURL_INDEX?>/vote/subscribe?vid=<?=$v->id?>">
	    		I want to say my word on this!
	    	</a>
	    </div>
	</div>
	<hr />
<?php } echo $this->foo; ?>